-- Gerado por scripts/seed-imoveis-2.mjs --sql
-- Imóveis com o mesmo título já cadastrado são pulados.

-- Lote Quintas do Sol, Lote 32, Quadra 32
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "tipo", "finalidadeUso", "preco", "area", "quartos", "banheiros", "vagas", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."banheiros", r."vagas", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Lote Quintas do Sol, Lote 32, Quadra 32","tipo":"lote-terreno","finalidadeUso":"Residencial","preco":1430000,"area":1305,"quartos":0,"banheiros":0,"vagas":0,"endereco":{"rua":"","numero":"","complemento":"Lote 32, Quadra 32","bairro":"Quintas do Sol","cidade":"","estado":"MG","cep":"","nomeCondominio":"Quintas do Sol"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Lote Quintas do Sol, Lote 32, Quadra 32');

-- Casa em Arraial d'Ajuda, BA
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Casa em Arraial d'Ajuda, BA","tipo":"casa-residencial","finalidadeUso":"Residencial","preco":3950000,"area":214,"quartos":4,"suites":2,"banheiros":0,"vagas":0,"endereco":{"rua":"Estrada da Balsa","numero":"","complemento":"","bairro":"Arraial d'Ajuda","cidade":"Porto Seguro","estado":"BA","cep":""}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Casa em Arraial d''Ajuda, BA');

-- Ed. Sergipe Residencial, Apto. 202
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "valorCondominio", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."valorCondominio", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Sergipe Residencial, Apto. 202","descricao":"Apartamento com área privativa de 115 m², com 2 quartos, sendo 1 suíte, no Edifício Sergipe Residencial, a poucos quarteirões da Avenida Afonso Pena e da Praça da Liberdade. Prédio de 2019, com duas torres, elevador, salão de festas e espaço gourmet.","tipo":"apto-area-privativa","finalidadeUso":"Residencial","preco":1250000,"area":115,"quartos":2,"suites":1,"banheiros":3,"vagas":2,"anoConstrucao":2019,"valorCondominio":1090,"caracteristicasEdificio":{"elevadorsocial":true,"salaodefestas":true,"churrasqueira":true,"gasCanalizado":true,"andarApartamento":2},"endereco":{"rua":"Rua Sergipe","numero":"319","complemento":"Apto 202","bairro":"Boa Viagem","cidade":"Belo Horizonte","estado":"MG","cep":"","nomeCondominio":"Ed. Sergipe Residencial"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Sergipe Residencial, Apto. 202');

-- Ed. Rio Branco Residencial, Apto. 503
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "valorCondominio", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."valorCondominio", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Rio Branco Residencial, Apto. 503","descricao":"Apartamento com área privativa no Rio Branco Residencial, edifício da EPO Empreendimentos com projeto de Gustavo Penna, no ponto mais central da Savassi. São 80 m² internos e 73 m² de área privativa descoberta, com 2 suítes, sala para dois ambientes, lavabo e 3 vagas. Lazer completo com piscina aquecida coberta, fitness, sauna, espaço gourmet, salão de festas, pet care e bicicletário.","tipo":"apto-area-privativa","finalidadeUso":"Residencial","preco":2150000,"area":153,"quartos":2,"suites":2,"banheiros":3,"vagas":3,"anoConstrucao":2023,"valorCondominio":2032,"caracteristicasEdificio":{"piscina":true,"academia":true,"sauna":true,"salaodefestas":true,"playground":true,"bicicletario":true,"elevadorsocial":true,"portaria24h":true,"numeroPavimentos":17,"andarApartamento":5},"endereco":{"rua":"Rua Tomé de Souza","numero":"533","complemento":"Apto 503","bairro":"Savassi","cidade":"Belo Horizonte","estado":"MG","cep":"30140-131","nomeCondominio":"Ed. Rio Branco Residencial"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Rio Branco Residencial, Apto. 503');

-- Ed. Jardins, Apto. 503
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "caracteristicasImovel", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."caracteristicasImovel", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Jardins, Apto. 503","descricao":"Apartamento de 108 m² com 3 suítes, uma delas com closet, sala para três ambientes, lavabo e 2 vagas, no Jardins, edifício da Caparaó no Lourdes entregue em 2025. Lazer com piscinas adulto e infantil, sauna e spa, espaço gourmet, fitness coberto e descoberto, salão de festas, playground, home office e sala de reunião.","tipo":"apartamento","finalidadeUso":"Residencial","preco":2900000,"area":108,"quartos":3,"suites":3,"banheiros":4,"vagas":2,"anoConstrucao":2025,"caracteristicasImovel":{"closet":true,"lavabo":true,"areaDeServico":true},"caracteristicasEdificio":{"piscina":true,"sauna":true,"academia":true,"salaodefestas":true,"playground":true,"bicicletario":true,"elevadorsocial":true,"portaria24h":true,"andarApartamento":5},"endereco":{"rua":"Rua Curitiba","numero":"2142","complemento":"Apto 503","bairro":"Lourdes","cidade":"Belo Horizonte","estado":"MG","cep":"30170-127","nomeCondominio":"Ed. Jardins"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Jardins, Apto. 503');

-- Ed. Jardins, Apto. 504
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "caracteristicasImovel", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."caracteristicasImovel", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Jardins, Apto. 504","descricao":"Apartamento de 108 m² com 3 suítes, uma delas com closet, sala para três ambientes, lavabo e 2 vagas, no Jardins, edifício da Caparaó no Lourdes entregue em 2025. Lazer com piscinas adulto e infantil, sauna e spa, espaço gourmet, fitness coberto e descoberto, salão de festas, playground, home office e sala de reunião.","tipo":"apartamento","finalidadeUso":"Residencial","preco":2900000,"area":108,"quartos":3,"suites":3,"banheiros":4,"vagas":2,"anoConstrucao":2025,"caracteristicasImovel":{"closet":true,"lavabo":true,"areaDeServico":true},"caracteristicasEdificio":{"piscina":true,"sauna":true,"academia":true,"salaodefestas":true,"playground":true,"bicicletario":true,"elevadorsocial":true,"portaria24h":true,"andarApartamento":5},"endereco":{"rua":"Rua Curitiba","numero":"2142","complemento":"Apto 504","bairro":"Lourdes","cidade":"Belo Horizonte","estado":"MG","cep":"30170-127","nomeCondominio":"Ed. Jardins"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Jardins, Apto. 504');

-- Ed. Soul, Apto. 703
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "caracteristicasImovel", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."caracteristicasImovel", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Soul, Apto. 703","descricao":"Apartamento de 116 m² com 3 suítes, lavabo, sala para três ambientes e 2 vagas, no Soul Savassi, edifício da Caparaó na Rua Pernambuco. Lazer completo com piscinas, quadra de beach tennis, fitness, sauna, espaço gourmet, salão de festas, espaço zen, espaço beauty, playground e coworking.","tipo":"apartamento","finalidadeUso":"Residencial","preco":2500000,"area":116,"quartos":3,"suites":3,"banheiros":4,"vagas":2,"anoConstrucao":2026,"caracteristicasImovel":{"lavabo":true,"areaDeServico":true},"caracteristicasEdificio":{"piscina":true,"sauna":true,"academia":true,"salaodefestas":true,"playground":true,"quadraAreia":true,"elevadorsocial":true,"numeroPavimentos":35,"andarApartamento":7},"endereco":{"rua":"Rua Pernambuco","numero":"909","complemento":"Apto 703","bairro":"Savassi","cidade":"Belo Horizonte","estado":"MG","cep":"30130-155","nomeCondominio":"Ed. Soul"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Soul, Apto. 703');

-- Ed. Soul, Apto. 704
insert into public.imoveis ("dataCadastro", "finalidade", "status", "fotos", "aceitaProposta", "titulo", "descricao", "tipo", "finalidadeUso", "preco", "area", "quartos", "suites", "banheiros", "vagas", "anoConstrucao", "caracteristicasImovel", "caracteristicasEdificio", "endereco")
select r."dataCadastro", r."finalidade", r."status", r."fotos", r."aceitaProposta", r."titulo", r."descricao", r."tipo", r."finalidadeUso", r."preco", r."area", r."quartos", r."suites", r."banheiros", r."vagas", r."anoConstrucao", r."caracteristicasImovel", r."caracteristicasEdificio", r."endereco"
from jsonb_populate_record(null::public.imoveis, $json${"dataCadastro":"2026-09-28T22:33:14.617Z","finalidade":"Comprar","status":"Ativo","fotos":[],"aceitaProposta":true,"titulo":"Ed. Soul, Apto. 704","descricao":"Apartamento de 116 m² com 3 suítes, lavabo, sala para três ambientes e 2 vagas, no Soul Savassi, edifício da Caparaó na Rua Pernambuco. Lazer completo com piscinas, quadra de beach tennis, fitness, sauna, espaço gourmet, salão de festas, espaço zen, espaço beauty, playground e coworking.","tipo":"apartamento","finalidadeUso":"Residencial","preco":2500000,"area":116,"quartos":3,"suites":3,"banheiros":4,"vagas":2,"anoConstrucao":2026,"caracteristicasImovel":{"lavabo":true,"areaDeServico":true},"caracteristicasEdificio":{"piscina":true,"sauna":true,"academia":true,"salaodefestas":true,"playground":true,"quadraAreia":true,"elevadorsocial":true,"numeroPavimentos":35,"andarApartamento":7},"endereco":{"rua":"Rua Pernambuco","numero":"909","complemento":"Apto 704","bairro":"Savassi","cidade":"Belo Horizonte","estado":"MG","cep":"30130-155","nomeCondominio":"Ed. Soul"}}$json$::jsonb) r
where not exists (select 1 from public.imoveis where titulo = 'Ed. Soul, Apto. 704');

